


export const MODEL_NAME = 'gemini-2.5-flash';

export const DEFAULT_TEST_CODE = `// Write your unit tests here using Mocha & Chai
// The DOM is available. You can query elements generated by your code.

describe('App Component', () => {
  it('should render the app container', () => {
    const app = document.getElementById('root') || document.getElementById('app');
    expect(app).to.exist;
  });

  it('should have a title or heading', () => {
    const headings = document.querySelectorAll('h1, h2, h3');
    expect(headings.length).to.be.greaterThan(0);
  });
});
`;

export const FRAMEWORKS = {
  tailwind: {
    name: 'Tailwind CSS',
    value: 'tailwind',
    scripts: '<script src="https://cdn.tailwindcss.com"></script>',
    instructions: `
      1. Use Tailwind CSS classes for styling. 
      2. Design for "Dark Mode" by default unless specified otherwise. 
      3. Use sleek, modern aesthetics (colors: slate, zinc, indigo).
      4. No extra setup required, just standard HTML/React with classNames.
    `
  },
  'material-ui': {
    name: 'Material UI',
    value: 'material-ui',
    scripts: `
      <script src="https://unpkg.com/react@18/umd/react.development.js"></script>
      <script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>
      <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
      <script src="https://unpkg.com/@mui/material@5.15.11/umd/material-ui.development.js"></script>
      <script src="https://unpkg.com/@emotion/react@11.11.3/dist/emotion-react.umd.min.js"></script>
      <script src="https://unpkg.com/@emotion/styled@11.11.0/dist/emotion-styled.umd.min.js"></script>
      <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet" />
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
    `,
    instructions: `
      1. Use Material UI (MUI) v5 components.
      2. Access components via the global 'MaterialUI' object (e.g., const { Button, Container } = MaterialUI;).
      3. Wrap your App in <MaterialUI.ThemeProvider theme={MaterialUI.createTheme({ palette: { mode: 'dark' } })}> and <MaterialUI.CssBaseline />.
      4. Do NOT use import statements. Destructure from globals.
    `
  },
  'chakra-ui': {
    name: 'Chakra UI',
    value: 'chakra-ui',
    scripts: `
      <script src="https://unpkg.com/react@18/umd/react.development.js"></script>
      <script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>
      <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
      <script src="https://unpkg.com/framer-motion@10.18.0/dist/framer-motion.js"></script>
      <script src="https://unpkg.com/@chakra-ui/react@2.8.2/dist/chakra-ui.min.js"></script>
      <script src="https://unpkg.com/@emotion/react@11.11.3/dist/emotion-react.umd.min.js"></script>
      <script src="https://unpkg.com/@emotion/styled@11.11.0/dist/emotion-styled.umd.min.js"></script>
    `,
    instructions: `
      1. Use Chakra UI v2 components.
      2. Access components via the global 'ChakraUI' object (e.g., const { Button, Box, ChakraProvider } = ChakraUI;).
      3. Wrap your App in <ChakraProvider>.
      4. Use Chakra's style props (e.g., bg="gray.800", color="white").
      5. Do NOT use import statements. Destructure from globals.
    `
  },
  bootstrap: {
    name: 'Bootstrap',
    value: 'bootstrap',
    scripts: `
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    `,
    instructions: `
      1. Use Bootstrap 5 classes for styling.
      2. Use 'data-bs-theme="dark"' on the body or container for dark mode.
      3. Use standard Bootstrap components.
    `
  }
};

export const getSystemInstruction = (frameworkValue: string = 'tailwind', skills: string = '') => {
  const framework = FRAMEWORKS[frameworkValue as keyof typeof FRAMEWORKS] || FRAMEWORKS.tailwind;
  
  return `
You are VibeCoder, an elite frontend engineer and creative coder. 
Your goal is to help the user build web interfaces, components, and mini-apps instantly.

YOU ARE CONFIGURED TO USE: ${framework.name}

RULES:
1. When the user asks for UI, an app, or a visual component, ALWAYS generate a SINGLE-FILE HTML solution.
2. The HTML file must include all necessary CSS and JS within the file.
3. Wrap your code in \`\`\`html ... \`\`\` blocks.
4. If using React, use the Babel standalone script and type="text/babel".
5. Be concise in your explanations. Focus on the code.
6. If you are updating existing code, output the FULL updated file so the preview remains complete.

FRAMEWORK SPECIFIC INSTRUCTIONS:
${framework.instructions}

REQUIRED HEADERS/SCRIPTS (Include these in your <head>):
${framework.scripts}

ACTIVE SKILLS (Apply these instructions to your output):
${skills}

Example of expected code structure for React (Tailwind example):
\`\`\`html
<!DOCTYPE html>
<html>
<head>
  <script src="https://cdn.tailwindcss.com"></script>
  <script src="https://unpkg.com/react@18/umd/react.development.js"></script>
  <script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
</head>
<body class="bg-slate-900 text-white p-4">
  <div id="app"></div>
  <script type="text/babel">
    function App() {
      return <div className="p-4 border border-slate-700 rounded">Hello VibeCoder</div>;
    }
    const root = ReactDOM.createRoot(document.getElementById('app'));
    root.render(<App />);
  </script>
</body>
</html>
\`\`\`
`;
};